// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6Ow-mX3XUUmhxKXFpaM1iw-SZ3gzNjF0',
    appId: '1:23427941715:web:38e0f1294c6ab8081f0da6',
    messagingSenderId: '23427941715',
    projectId: 'ecommerce-97ebb',
    authDomain: 'ecommerce-97ebb.firebaseapp.com',
    storageBucket: 'ecommerce-97ebb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlQUBmhc9MYb8rN8AyLQUfvIwrrUw0MS4',
    appId: '1:23427941715:android:c9d8405bd26513b31f0da6',
    messagingSenderId: '23427941715',
    projectId: 'ecommerce-97ebb',
    storageBucket: 'ecommerce-97ebb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsZZMMcOhhUnouHQSF5PDdOMF2MFDOU5M',
    appId: '1:23427941715:ios:3c778d923b3702b51f0da6',
    messagingSenderId: '23427941715',
    projectId: 'ecommerce-97ebb',
    storageBucket: 'ecommerce-97ebb.appspot.com',
    androidClientId: '23427941715-p5br9q1e8s96f4soqk7iuj018mlrvan9.apps.googleusercontent.com',
    iosClientId: '23427941715-gthbuc3rtq217dm9djv68o58inarf9ra.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDo',
  );
}
